### ISSUE TITLE
scala.MatchError: spoiler

### ISSUE THREAD

**Issue by benkio** [apimorphism/telegramium#242]
Hi, 
I write this issue since I found my bots failing on start because of the error `scala.MatchError: spoiler (of class java.lang.String)`
Analyzing the stack trace, it seems to be related to the library.
Could you please check what could be the cause? 🙏 
I'm using version `7.55.0`

```
[error] scala.MatchError: spoiler (of class java.lang.String)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$messageentityDecoder$2(package.scala:2221)
[error] 	at io.circe.Decoder$$anon$2.apply(Decoder.scala:111)
[error] 	at io.circe.SeqDecoder.apply(SeqDecoder.scala:17)
[error] 	at io.circe.Decoder$$anon$39.tryDecode(Decoder.scala:930)
[error] 	at io.circe.ACursor.as(ACursor.scala:211)
[error] 	at io.circe.ACursor.get(ACursor.scala:218)
[error] 	at io.circe.ACursor.getOrElse(ACursor.scala:227)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$messageDecoder$20(package.scala:4118)
[error] 	at scala.util.Either.flatMap(Either.scala:352)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$messageDecoder$19(package.scala:4117)
[error] 	at scala.util.Either.flatMap(Either.scala:352)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$messageDecoder$18(package.scala:4116)
[error] 	at scala.util.Either.flatMap(Either.scala:352)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$messageDecoder$17(package.scala:4115)
[error] 	at scala.util.Either.flatMap(Either.scala:352)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$messageDecoder$16(package.scala:4114)
[error] 	at scala.util.Either.flatMap(Either.scala:352)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$messageDecoder$15(package.scala:4113)
[error] 	at scala.util.Either.flatMap(Either.scala:352)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$messageDecoder$14(package.scala:4112)
[error] 	at scala.util.Either.flatMap(Either.scala:352)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$messageDecoder$13(package.scala:4111)
[error] 	at scala.util.Either.flatMap(Either.scala:352)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$messageDecoder$12(package.scala:4110)
[error] 	at scala.util.Either.flatMap(Either.scala:352)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$messageDecoder$11(package.scala:4109)
[error] 	at scala.util.Either.flatMap(Either.scala:352)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$messageDecoder$10(package.scala:4108)
[error] 	at scala.util.Either.flatMap(Either.scala:352)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$messageDecoder$9(package.scala:4107)
[error] 	at scala.util.Either.flatMap(Either.scala:352)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$messageDecoder$8(package.scala:4106)
[error] 	at scala.util.Either.flatMap(Either.scala:352)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$messageDecoder$7(package.scala:4105)
[error] 	at scala.util.Either.flatMap(Either.scala:352)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$messageDecoder$6(package.scala:4104)
[error] 	at scala.util.Either.flatMap(Either.scala:352)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$messageDecoder$5(package.scala:4103)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$messageDecoder$5$adapted(package.scala:4102)
[error] 	at scala.util.Either.flatMap(Either.scala:352)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$messageDecoder$4(package.scala:4102)
[error] 	at scala.util.Either.flatMap(Either.scala:352)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$messageDecoder$3(package.scala:4101)
[error] 	at scala.util.Either.flatMap(Either.scala:352)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$messageDecoder$2(package.scala:4100)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$messageDecoder$2$adapted(package.scala:4099)
[error] 	at scala.util.Either.flatMap(Either.scala:352)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$messageDecoder$1(package.scala:4099)
[error] 	at io.circe.Decoder$$anon$16.apply(Decoder.scala:493)
[error] 	at io.circe.Decoder$$anon$39.tryDecode(Decoder.scala:930)
[error] 	at io.circe.ACursor.as(ACursor.scala:211)
[error] 	at io.circe.ACursor.get(ACursor.scala:218)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$updateDecoder$2(package.scala:2995)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$updateDecoder$2$adapted(package.scala:2994)
[error] 	at scala.util.Either.flatMap(Either.scala:352)
[error] 	at telegramium.bots.CirceImplicits$.$anonfun$updateDecoder$1(package.scala:2994)
[error] 	at io.circe.Decoder$$anon$16.apply(Decoder.scala:493)
[error] 	at io.circe.SeqDecoder.apply(SeqDecoder.scala:17)
[error] 	at io.circe.Decoder$$anon$39.tryDecode(Decoder.scala:930)
[error] 	at io.circe.ACursor.as(ACursor.scala:211)
[error] 	at io.circe.ACursor.get(ACursor.scala:218)
[error] 	at telegramium.bots.high.BotApi.$anonfun$responseDecoder$2(BotApi.scala:56)
[error] 	at telegramium.bots.high.BotApi.$anonfun$responseDecoder$2$adapted(BotApi.scala:55)
[error] 	at scala.util.Either.flatMap(Either.scala:352)
[error] 	at telegramium.bots.high.BotApi.$anonfun$responseDecoder$1(BotApi.scala:55)
[error] 	at io.circe.Decoder$$anon$16.apply(Decoder.scala:493)
[error] 	at io.circe.Decoder.decodeJson(Decoder.scala:88)
[error] 	at io.circe.Decoder.decodeJson$(Decoder.scala:88)
[error] 	at io.circe.Decoder$$anon$16.decodeJson(Decoder.scala:492)
[error] 	at org.http4s.circe.CirceInstances.$anonfun$jsonOfWithMediaHelper$1(CirceInstances.scala:109)
[error] 	at cats.data.EitherT.$anonfun$flatMap$1(EitherT.scala:405)
[error] 	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
[error] 	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
[error] 	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
[error] 	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
[error] 	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
[error] 	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
[error] 	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
[error] 	at rethrow$extension @ fs2.Compiler$Target.$anonfun$compile$1(Compiler.scala:156)
[error] 	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
[error] 	at flatMap @ fs2.Pull$.$anonfun$compile$21(Pull.scala:1153)
[error] 	at update @ fs2.internal.Scope.releaseChildScope(Scope.scala:224)
[error] 	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
[error] 	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
```

**Comment by benkio** [comment]
Update: 
upgrading to `7.56.0` solved the issue :D
